# Generated by Django 4.2.6 on 2023-10-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("attack", models.FloatField(default=0)),
                ("attack_percent", models.FloatField(default=0)),
                ("defense", models.FloatField(default=0)),
                ("defense_percent", models.FloatField(default=0)),
                ("health", models.FloatField(default=0)),
                ("health_percent", models.FloatField(default=0)),
                ("critical_rate", models.FloatField(default=0)),
                ("critical_damage", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("base_attack", models.FloatField()),
                ("base_defense", models.FloatField()),
                ("base_health", models.FloatField()),
                ("equipments", models.ManyToManyField(to="game.equipment")),
            ],
        ),
    ]
