# Generated by Django 4.2.6 on 2023-10-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
