# Generated by Django 4.2.6 on 2023-11-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_equipment_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="attack",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="attack_percent",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="critical_damage",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="critical_rate",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="defense",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="defense_percent",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="health",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="health_percent",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="level",
        ),
        migrations.AlterField(
            model_name="role",
            name="base_attack",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="role",
            name="base_defense",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="role",
            name="base_health",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="EquipmentEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=0)),
                ("attack", models.FloatField(default=0)),
                ("attack_percent", models.FloatField(default=0)),
                ("defense", models.FloatField(default=0)),
                ("defense_percent", models.FloatField(default=0)),
                ("health", models.FloatField(default=0)),
                ("health_percent", models.FloatField(default=0)),
                ("critical_rate", models.FloatField(default=0)),
                ("critical_damage", models.FloatField(default=0)),
                (
                    "equipment_prototype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.equipment"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="role",
            name="equipments",
            field=models.ManyToManyField(to="game.equipmententity"),
        ),
    ]
