# Generated by Django 4.2.6 on 2023-11-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_remove_equipment_attack_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="equipments",
        ),
        migrations.AddField(
            model_name="equipmententity",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipments",
                to="game.role",
            ),
        ),
    ]
