# Generated by Django 4.2.6 on 2023-11-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_remove_role_equipments_equipmententity_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="base_critical_damage",
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name="role",
            name="base_critical_rate",
            field=models.FloatField(default=5),
        ),
    ]
