# Generated by Django 4.2.7 on 2023-11-27 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_role_base_critical_damage_role_base_critical_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='birth',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='base_attack',
            field=models.FloatField(default=156.20684148533263),
        ),
        migrations.AlterField(
            model_name='role',
            name='base_critical_damage',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='base_defense',
            field=models.FloatField(default=302.1229801122598),
        ),
        migrations.AlterField(
            model_name='role',
            name='base_health',
            field=models.FloatField(default=2958.068015423529),
        ),
    ]
