# Generated by Django 4.2.7 on 2023-11-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_role_birth_alter_role_base_attack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='base_attack',
            field=models.FloatField(default=276.48651728872227),
        ),
        migrations.AlterField(
            model_name='role',
            name='base_defense',
            field=models.FloatField(default=170.78613849584133),
        ),
        migrations.AlterField(
            model_name='role',
            name='base_health',
            field=models.FloatField(default=2299.4550994859005),
        ),
    ]
